brand: &brand magenx
codename: cloud

budget_limit_amount: "800"

domain: &domain "magenx.cloud"
san: &san
  - "*.magenx.cloud"
aliases: 
  - *domain
  - *san

sns:
  topic:
    budget:
      email: 
        - "admin@magenx.cloud"
    devops:
      email:
        - "admin@magenx.cloud"
    security:
      email:
        - "admin@magenx.cloud"

vpc:
  cidr_block: "10.0.0.0/16"
  availability_zone_total: &availability_zone_total 2
  enable_dns_support: true
  enable_dns_hostnames: true
  instance_tenancy: default
  create_database_subnet: true
  exclude_zone_ids:
    - "use1-az3"

nat_gateway:
  instance_type: "t4g.nano"
  ami_owner: "136693071363"
  ami_image: "debian-12-arm64*"
  volume_size: 10
  firewall: true

managed_services: &create true

elasticache:
  create: *create
  engine: "valkey"
  engine_version: "8.2"
  cluster:
    session:
      node_type: "cache.t4g.micro"
      num_cache_clusters: *availability_zone_total
      transit_encryption_enabled: true
      at_rest_encryption_enabled: true
      maintenance_window: "sun:05:00-sun:09:00"
      apply_immediately: true
    cache:
      node_type: "cache.t4g.micro"
      num_cache_clusters: *availability_zone_total
      transit_encryption_enabled: true
      at_rest_encryption_enabled: true
      maintenance_window: "sun:05:00-sun:09:00"
      apply_immediately: true
  parameter_group_family: "valkey8"
  parameters:
    maxmemory-policy: "allkeys-lru"
  metrics:
    cpu:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "3"
      metric_name: "CPUUtilization"
      namespace: "AWS/ElastiCache"
      period: "60"
      statistic: "Average"
      threshold: "80"
      dimensions: ""
    memory:
      comparison_operator: "LessThanThreshold"
      evaluation_periods: "3"
      metric_name: "FreeableMemory"
      namespace: "AWS/ElastiCache"
      period: "60"
      statistic: "Average"
      threshold: "10000000"
      dimensions: ""
    evictions:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "3"
      metric_name: "Evictions"
      namespace: "AWS/ElastiCache"
      period: "60"
      statistic: "Sum"
      threshold: "10"
      dimensions: ""
    connections:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "3"
      metric_name: "CurrConnections"
      namespace: "AWS/ElastiCache"
      period: "60"
      statistic: "Average"
      threshold: "1000"
      dimensions: ""

rabbitmq:
  create: *create
  engine_version: "3.13"
  deployment_mode: "SINGLE_INSTANCE" # "CLUSTER_MULTI_AZ" "ACTIVE_STANDBY_MULTI_AZ"
  host_instance_type: "mq.t3.micro"
  publicly_accessible: false
  apply_immediately: true
  auto_minor_version_upgrade: true
  maintenance_window_start_time:
    day_of_week: "SUNDAY"
    time_of_day: "00:30"
    time_zone: "GMT"
  encryption_options:
    use_aws_owned_key: false
  logs:
    general: true

opensearch:
  create: *create
  engine_version: "OpenSearch_2.19"
  auto_software_update_enabled: false
  instance_type: "t3.small.search"
  auto_tune_options:
    desired_state: "DISABLED"
  instance_count: *availability_zone_total
  multi_az_with_standby_enabled: false
  tls_security_policy: "Policy-Min-TLS-1-2-PFS-2023-10"
  ebs_enabled: true
  volume_type: "gp3"
  volume_size: "50"
  ip_address_type: "ipv4"
  dedicated_master_enabled: false
  dedicated_master_type: "r7g.medium.search"
  warm_enabled: false
  warm_count: *availability_zone_total
  warm_type: "ultrawarm1.medium.search"
  node_options:
    node_config:
      enabled: false
      count: *availability_zone_total
      type: "r7g.medium.search"
  metrics:
    cluster:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "1"
      metric_name: "ClusterStatus.red"
      namespace: "AWS/ES"
      period: "60"
      statistic: "Maximum"
      threshold: "0"
      dimensions: ""
    memory:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "2"
      metric_name: "JVMMemoryPressure"
      namespace: "AWS/ES"
      period: "60"
      statistic: "Maximum"
      threshold: "85"
      dimensions: ""
    disk:
      comparison_operator: "LessThanThreshold"
      evaluation_periods: "2"
      metric_name: "FreeStorageSpace"
      namespace: "AWS/ES"
      period: "300"
      statistic: "Minimum"
      threshold: "20480"
      dimensions: ""

aurora:
  create: *create
  storage_type: "gp3"
  storage_encrypted: true
  instance_class: "db.t3.medium"
  engine: "aurora-mysql"
  engine_version: "8.0"
  skip_final_snapshot: true
  enabled_cloudwatch_logs_exports: ["audit", "error", "general", "slowquery"]
  cluster_performance_insights_enabled: true
  cluster_performance_insights_retention_period: 7
  manage_master_user_password: false
  manage_master_user_password_rotation: false
  master_user_password_rotation_automatically_after_days: 30
  master_username: *brand
  database_name: *brand
  db_cluster_parameter_group_family: "aurora-mysql8.0"
  copy_tags_to_snapshot: true
  backup_retention_period: "30"
  delete_automated_backups: true
  deletion_protection: false
  autoscaling_enabled: true
  autoscaling_min_capacity: 1
  autoscaling_max_capacity: *availability_zone_total
  apply_immediately: true
  parameters:
    log_bin_trust_function_creators: 1
    max_allowed_packet: 268435456
    max_connect_errors: 10000
    interactive_timeout: 120
    wait_timeout: 300
    innodb_lock_wait_timeout: 60
    tmp_table_size: "{DBInstanceClassMemory/512}"
    max_heap_table_size: "{DBInstanceClassMemory/512}"
  metrics:
    cpu:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "2"
      metric_name: "CPUUtilization"
      namespace: "AWS/RDS"
      period: "60"
      statistic: "Average"
      threshold: "80"
      dimensions: ""
    memory:
      comparison_operator: "LessThanThreshold"
      evaluation_periods: "2"
      metric_name: "FreeableMemory"
      namespace: "AWS/RDS"
      period: "60"
      statistic: "Average"
      threshold: "120480"
      dimensions: ""
    connections:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "2"
      metric_name: "DatabaseConnections"
      namespace: "AWS/RDS"
      period: "60"
      statistic: "Average"
      threshold: "150"
      dimensions: ""
    disk:
      comparison_operator: "LessThanThreshold"
      evaluation_periods: 2
      metric_name: "FreeStorageSpace"
      namespace: "AWS/RDS"
      period: "300"
      statistic: "Minimum"
      threshold: "20480"
      dimensions: ""

rds:
  create: false
  engine: "mysql"
  engine_version: "8.0"
  family: "mysql8.0"
  major_engine_version: "8.0"
  instance_class: "db.t3.micro"
  allocated_storage: 20
  max_allocated_storage: 100
  port: 3306
  multi_az: false
  db_name: *brand
  username: *brand
  manage_master_user_password: false
  manage_master_user_password_rotation: false
  master_user_password_rotation_automatically_after_days: 30
  maintenance_window: "Mon:03:00-Mon:04:00"
  backup_window: "01:00-02:00"
  enabled_cloudwatch_logs_exports: ["general", "error", "slowquery"]
  create_db_option_group: true
  create_db_parameter_group: true
  create_cloudwatch_log_group: true
  create_monitoring_role: true
  monitoring_interval: 60
  performance_insights_enabled: true
  performance_insights_retention_period: 7
  skip_final_snapshot: false
  deletion_protection: true
  parameters:
    log_bin_trust_function_creators: 1
    max_allowed_packet: 268435456
    max_connect_errors: 10000
    interactive_timeout: 120
    wait_timeout: 300
    innodb_lock_wait_timeout: 60
    tmp_table_size: "{DBInstanceClassMemory/512}"
    max_heap_table_size: "{DBInstanceClassMemory/512}"
  metrics:
    cpu:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "2"
      metric_name: "CPUUtilization"
      namespace: "AWS/RDS"
      period: "60"
      statistic: "Average"
      threshold: "80"
      dimensions: ""
    memory:
      comparison_operator: "LessThanThreshold"
      evaluation_periods: "2"
      metric_name: "FreeableMemory"
      namespace: "AWS/RDS"
      period: "60"
      statistic: "Average"
      threshold: "120480"
      dimensions: ""
    connections:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "2"
      metric_name: "DatabaseConnections"
      namespace: "AWS/RDS"
      period: "60"
      statistic: "Average"
      threshold: "150"
      dimensions: ""
    disk:
      comparison_operator: "LessThanThreshold"
      evaluation_periods: 2
      metric_name: "FreeStorageSpace"
      namespace: "AWS/RDS"
      period: "300"
      statistic: "Minimum"
      threshold: "20480"
      dimensions: ""

alb:
  ssl_policy: "ELBSecurityPolicy-TLS13-1-2-Res-2021-06"
  enable_deletion_protection: false
  target_type: "ip"
  health_check_path: "/health_check.php"
  fixed_response:
    status_code: "418"
    message_body: "No targets are responding to this request"
  metrics:
    high_5xx_errors:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "2"
      metric_name: "HTTPCode_Target_5XX_Count"
      namespace: "AWS/ApplicationELB"
      period: "120"
      statistic: "Sum"
      threshold: "50"
      dimensions: "LoadBalancer"
    high_target_response_time:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "3"
      metric_name: "TargetResponseTime"
      namespace: "AWS/ApplicationELB"
      period: "120"
      statistic: "Average"
      threshold: "2.0"
      dimensions: "LoadBalancer"
    unhealthy_hosts:
      comparison_operator: "LessThanThreshold"
      evaluation_periods: "2"
      metric_name: "HealthyHostCount"
      namespace: "AWS/ApplicationELB"
      period: "120"
      statistic: "Average"
      threshold: *availability_zone_total
      dimensions: "LoadBalancer"
    elb_5xx_errors:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "1"
      metric_name: "HTTPCode_ELB_5XX_Count"
      namespace: "AWS/ApplicationELB"
      period: "60"
      statistic: "Sum"
      threshold: "5"
      dimensions: "LoadBalancer"

ecs:
  cluster:
    minimum_scaling_step_size: 1
    maximum_scaling_step_size: 6
    target_capacity: 70
    cpu: 2048
    memory: 4096
    cpu_architecture: "ARM64"
  container:
    varnish:
      image: "varnish:latest"
      port: 80
      protocol: "tcp"
      instance_type: "t4g.micro"
      volume_size: 10
      cpu: 2048
      memory: 4096
      desired_capacity: 1
      min_size: 1
      max_size: 2
      secrets:
    backend:
      image: "backend:latest"
      port: 80
      protocol: "tcp"
      instance_type: "t4g.micro"
      volume_size: 25
      cpu: 2048
      memory: 4096
      desired_capacity: 2
      min_size: 2
      max_size: 6
      secrets:
        - DATABASE_IDENTIFIER
        - DATABASE_PASSWORD

asg:
  health_check_type: "EC2"
  protect_from_scale_in: false
  instance_warmup: 60
  use_mixed_instances_policy: true
  mixed_instances_policy:
    spot_allocation_strategy: "price-capacity-optimized"
  override:
    instance_requirements:
      vcpu_count:
        min: 2
        max: 4
      memory_mib:
        min: 4096
        max: 8192
      instance_generations: ["current"]
      burstable_performance: "included"
  metrics:
    disk:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "2"
      metric_name: "disk_used_percent"
      namespace: "backend"
      period: "120"
      statistic: "Average"
      threshold: "80"
      dimensions: "AutoScalingGroupName"
    max_instances:
      comparison_operator: "GreaterThanOrEqualToThreshold"
      evaluation_periods: "1"
      metric_name: "GroupInServiceInstances"
      namespace: "AWS/AutoScaling"
      period: "60"
      statistic: "Maximum"
      threshold: *availability_zone_total
      dimensions: "AutoScalingGroupName"

s3:
  bucket:
    media:
      versioning: false
      eventbridge: false
      policy: "media_bucket_policy"
      intelligent_tiering:
        status: "Enabled"
      lifecycle_rule:
        status: "Enabled"
    system:
      versioning: false
      eventbridge: false
      policy: "system_bucket_policy"
      intelligent_tiering:
        status: "Disabled"
      lifecycle_rule:
        status: "Disabled"
    backup:
      eventbridge: true
      versioning: true
      policy: "backup_bucket_policy"
      intelligent_tiering:
        status: "Disabled"
      lifecycle_rule:
        status: "Disabled"
    logs:
      versioning: false
      eventbridge: false
      policy: "logs_bucket_policy"
      intelligent_tiering:
        status: "Enabled"
      lifecycle_rule:
        status: "Enabled"

efs:
  public:
    uid: "1001"
    gid: "1002"
    permissions: "2770"
  shared:
    uid: "1001"
    gid: "1002"
    permissions: "2770"
  releases:
    uid: "1001"
    gid: "1002"
    permissions: "2770"

cloudfront:
  staging: false
  wait_for_deployment: false
  http_version: "http2and3"
  price_class: "PriceClass_100"
  origin_shield_enabled: true
  origin_ssl_protocols: "TLSv1.2"
  retain_on_delete: false
  is_ipv6_enabled: true
  minimum_protocol_version: "TLSv1.3_2025"
  path_pattern: "/media/catalog/product/*"
  failover_criteria_status_codes: [403, 404, 500, 503, 504]
  create_monitoring_subscription: true

waf:
  restricted_countries: [CN, RU, IR, KP, SD, SY, CU]
  whitelist_ip:
    - "66.249.68.2/32"
    - "192.30.252.0/22"
    - "185.199.108.0/22"
    - "140.82.112.0/20"
  blacklist_ip:
    - "47.79.0.0/17"
    - "47.79.128.0/19"
    - "47.80.0.0/15"
    - "47.82.0.0/17"
    - "47.83.0.0/16"


lambda:
  memory_size: 2048
  timeout: 60
  invoke_mode: "RESPONSE_STREAM"
  tracing_mode: "Active"
  cloudwatch_logs_retention_in_days: 30
  logging_log_format: "JSON"
  imgproxy: "imgproxy:latest"

imgproxy:
  port: "8080"
  use_s3: true
  allow_insecure: true
  allow_origin: *domain
  allowed_sources: "s3://,local://"
  allowed_processing_options: "rs,fit,wm,soea"
  fallback_image_path: ""
  watermark_path: ""
  max_redirects: 1
  ttl: "31536000"
  auto_webp: true
  auto_avif: true
  quality: "70"
  format_quality: "jpeg=70,avif=40,webp=60"
  use_etag: true
  enable_debug_headers: true
  log_format: "json"
  log_level: "warn"
  cloud_watch_service_name: "imgproxy"
  cloud_watch_namespace: "imgproxy"
  
