brand: magenx
codename: cloud

budget_limit_amount: "800"

domain: "magenx.cloud"
san: 
  - "*.magenx.cloud"
aliases: 
  - ""

vpc:
  cidr_block: "10.0.0.0/16"
  availability_zone_total: &availability_zone_total 2
  enable_dns_support: true
  enable_dns_hostnames: true
  instance_tenancy: default
  create_database_subnet: true
  exclude_zone_ids:
    - "use1-az3"

nat_gateway:
  instance_type: "t4g.nano"
  ami_owner: "136693071363"
  ami_image: "debian-12-arm64*"
  volume_size: 25
  firewall: true


sns:
  topic:
    budget:
      email: 
        - "admin@magenx.cloud"
    devops:
      email:
        - "admin@magenx.cloud"
    security:
      email:
        - "admin@magenx.cloud"


ec2:
  varnish:
    instance_type: "t4g.small"
    service: false
    volume_size: 25
    desired_capacity: *availability_zone_total
    min_size: *availability_zone_total
    max_size: *availability_zone_total
  opensearch:
    instance_type: "t4g.small"
    service: true
    volume_size: 25
    desired_capacity: *availability_zone_total
    min_size: *availability_zone_total
    max_size: *availability_zone_total
  redis:
    instance_type: "t4g.small"
    service: true
    volume_size: 25
    desired_capacity: *availability_zone_total
    min_size: *availability_zone_total
    max_size: *availability_zone_total
  rabbitmq:
    instance_type: "t4g.nano"
    service: true
    volume_size: 25
    desired_capacity: *availability_zone_total
    min_size: *availability_zone_total
    max_size: *availability_zone_total


elasticache:
  create: true
  engine_version: "7.1"
  cluster:
    session:
      node_type: "cache.t4g.micro"
      num_cache_clusters: *availability_zone_total
      transit_encryption_enabled: true
      at_rest_encryption_enabled: true
      maintenance_window: "sun:05:00-sun:09:00"
      apply_immediately: true
    cache:
      node_type: "cache.t4g.micro"
      num_cache_clusters: *availability_zone_total
      transit_encryption_enabled: false
      at_rest_encryption_enabled: false
      maintenance_window: "sun:05:00-sun:09:00"
      apply_immediately: true
  parameter_group_family: "redis7"
  parameters:
    maxmemory-policy: "allkeys-lru"
  metrics:
    cpu:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "3"
      metric_name: "CPUUtilization"
      namespace: "AWS/ElastiCache"
      period: "60"
      statistic: "Average"
      threshold: "80"
    memory:
      comparison_operator: "LessThanThreshold"
      evaluation_periods: "3"
      metric_name: "FreeableMemory"
      namespace: "AWS/ElastiCache"
      period: "60"
      statistic: "Average"
      threshold: "10000000"
    evictions:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "3"
      metric_name: "Evictions"
      namespace: "AWS/ElastiCache"
      period: "60"
      statistic: "Sum"
      threshold: "10"
    connections:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "3"
      metric_name: "CurrConnections"
      namespace: "AWS/ElastiCache"
      period: "60"
      statistic: "Average"
      threshold: "1000"


opensearch:
  create: true
  engine_version: "OpenSearch_2.19"
  instance_type: "r7g.medium.search"
  instance_count: *availability_zone_total
  tls_security_policy: "Policy-Min-TLS-1-2-PFS-2023-10"
  ebs_enabled: true
  volume_type: "gp3"
  volume_size: "100"
  ip_address_type: "ipv4"
  auto_software_update_enabled: false
  dedicated_master_enabled: false
  dedicated_master_type: "r7g.medium.search"
  node_options:
    node_config: false
    count: *availability_zone_total
    type: "r7g.medium.search"
  metrics:
    cluster:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "1"
      metric_name: "ClusterStatus.red"
      namespace: "AWS/ES"
      period: "60"
      statistic: "Maximum"
      threshold: "0"
    memory:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "2"
      metric_name: "JVMMemoryPressure"
      namespace: "AWS/ES"
      period: "60"
      statistic: "Maximum"
      threshold: "85"
    disk:
      comparison_operator: "LessThanThreshold"
      evaluation_periods: "2"
      metric_name: "FreeStorageSpace"
      namespace: "AWS/ES"
      period: "300"
      statistic: "Minimum"
      threshold: "20480"


aurora:
  create: true
  storage_type: "gp3"
  storage_encrypted: true
  instance_class: "db.r6g.large"
  engine: "aurora-mysql"
  engine_version: "8.0"
  skip_final_snapshot: true
  enabled_cloudwatch_logs_exports: ["audit", "error", "general", "slowquery"]
  cluster_performance_insights_enabled: true
  cluster_performance_insights_retention_period: 7
  manage_master_user_password: false
  manage_master_user_password_rotation: false
  master_user_password_rotation_automatically_after_days: 30
  db_cluster_parameter_group_family: "aurora-mysql8.0"
  copy_tags_to_snapshot: true
  backup_retention_period: "30"
  delete_automated_backups: true
  deletion_protection: false
  autoscaling_enabled: true
  autoscaling_min_capacity: 1
  autoscaling_max_capacity: 2
  apply_immediately: true
  parameters:
    log_bin_trust_function_creators: 1
    max_allowed_packet: 268435456
    max_connect_errors: 10000
    interactive_timeout: 120
    wait_timeout: 300
    innodb_lock_wait_timeout: 60
    tmp_table_size: "{DBInstanceClassMemory/512}"
    max_heap_table_size: "{DBInstanceClassMemory/512}"
  metrics:
    cpu:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "2"
      metric_name: "CPUUtilization"
      namespace: "AWS/RDS"
      period: "60"
      statistic: "Average"
      threshold: "80"
    memory:
      comparison_operator: "LessThanThreshold"
      evaluation_periods: "2"
      metric_name: "FreeableMemory"
      namespace: "AWS/RDS"
      period: "60"
      statistic: "Average"
      threshold: "120480"
    connections:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "2"
      metric_name: "DatabaseConnections"
      namespace: "AWS/RDS"
      period: "60"
      statistic: "Average"
      threshold: "500"
    disk:
      comparison_operator: "LessThanThreshold"
      evaluation_periods: 2
      metric_name: "FreeStorageSpace"
      namespace: "AWS/RDS"
      period: "300"
      statistic: "Minimum"
      threshold: "20480"


rds:
  create: true
  engine: "mysql"
  engine_version: "8.0"
  family: "mysql8.0"
  major_engine_version: "8.0"
  instance_class: "db.t3.micro"
  allocated_storage: 20
  max_allocated_storage: 100
  port: 3306
  multi_az: false
  manage_master_user_password: true
  manage_master_user_password_rotation: true
  master_user_password_rotation_automatically_after_days: 30
  maintenance_window: "Mon:03:00-Mon:04:00"
  backup_window: "01:00-02:00"
  enabled_cloudwatch_logs_exports: ["general", "error", "slowquery"]
  create_cloudwatch_log_group: true
  monitoring_interval: 60
  create_monitoring_role: true
  performance_insights_enabled: true
  performance_insights_retention_period: 7
  skip_final_snapshot: false
  deletion_protection: true
  parameters:
    log_bin_trust_function_creators: 1
    max_allowed_packet: 268435456
    max_connect_errors: 10000
    interactive_timeout: 120
    wait_timeout: 300
    innodb_lock_wait_timeout: 60
    tmp_table_size: "{DBInstanceClassMemory/512}"
    max_heap_table_size: "{DBInstanceClassMemory/512}"
  metrics:
    cpu:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "2"
      metric_name: "CPUUtilization"
      namespace: "AWS/RDS"
      period: "60"
      statistic: "Average"
      threshold: "80"
    memory:
      comparison_operator: "LessThanThreshold"
      evaluation_periods: "2"
      metric_name: "FreeableMemory"
      namespace: "AWS/RDS"
      period: "60"
      statistic: "Average"
      threshold: "120480"
    connections:
      comparison_operator: "GreaterThanThreshold"
      evaluation_periods: "2"
      metric_name: "DatabaseConnections"
      namespace: "AWS/RDS"
      period: "60"
      statistic: "Average"
      threshold: "500"
    disk:
      comparison_operator: "LessThanThreshold"
      evaluation_periods: 2
      metric_name: "FreeStorageSpace"
      namespace: "AWS/RDS"
      period: "300"
      statistic: "Minimum"
      threshold: "20480" 
    

s3:
  bucket:
    lambda:
      versioning: true
      eventbridge: false
      policy: "lambda_bucket_policy"
      intelligent_tiering:
        status: "Disabled"
      lifecycle_rule:
        status: "Disabled"
    logs:
      versioning: false
      eventbridge: false
      policy: "logs_bucket_policy"
      intelligent_tiering:
        status: "Enabled"
      lifecycle_rule:
        status: "Enabled"
    media:
      versioning: false
      eventbridge: false
      policy: "media_bucket_policy"
      intelligent_tiering:
        status: "Enabled"
      lifecycle_rule:
        status: "Enabled"
    media-optimized:
      eventbridge: false
      versioning: false
      policy: "media_optimized_bucket_policy"
      intelligent_tiering:
        status: "Enabled"
      lifecycle_rule:
        status: "Enabled"
    system:
      versioning: false
      eventbridge: false
      policy: "system_bucket_policy"
      intelligent_tiering:
        status: "Disabled"
      lifecycle_rule:
        status: "Disabled"
    backup:
      eventbridge: true
      versioning: true
      policy: "backup_bucket_policy"
      intelligent_tiering:
        status: "Disabled"
      lifecycle_rule:
        status: "Disabled"


efs:
  var:
    uid: "1001"
    gid: "1002"
    permissions: "2770"
  media:
    uid: "1001"
    gid: "1002"
    permissions: "2770"


cloudfront:
  staging: false
  wait_for_deployment: false
  http_version: "http2and3"
  price_class: "PriceClass_100"
  origin_shield_enabled: true
  origin_ssl_protocols: "TLSv1.2"
  retain_on_delete: false
  is_ipv6_enabled: true
  minimum_protocol_version: "TLSv1.2_2021"
  path_pattern: "/media/catalog/product/*"
  failover_criteria_status_codes: [403, 404, 500, 503, 504]
  create_monitoring_subscription: true


alb:
  ssl_policy: "ELBSecurityPolicy-TLS13-1-2-Res-2021-06"
  enable_deletion_protection: false
  target_group: "frontend-ec2"
  target_type: "ip"
  health_check_path: "health_check.php"
  fixed_response:
    status_code: "418"
    message_body: "No targets are responding to this request"

asg:
  instance_type: "t4g.medium"
  health_check_type: "EC2"
  min_size: *availability_zone_total
  max_size: 4
  desired_capacity: 2

ecr:
  force_delete: true
  docker_image: "public.ecr.aws/docker/library/hello-world:latest"
  
ecs:
  container_name: "magenx-ecommerce-app"
  container_port: 80
  protocol: "tcp"
  cluster_cpu: 2048
  cluster_memory: 4096
  container_cpu: 2048
  container_memory: 4096
  cpu_architecture: "ARM64"

waf:
  restricted_countries: [CN, RU, IR, KP, SD, SY, CU]
  whitelist_ip:
    - "66.249.68.2/32"
    - "192.30.252.0/22"
    - "185.199.108.0/22"
    - "140.82.112.0/20"
  blacklist_ip:
    - "47.79.0.0/17"
    - "47.79.128.0/19"
    - "47.80.0.0/15"
    - "47.82.0.0/17"
    - "47.83.0.0/16"
